# Generated by Django 4.2.9 on 2024-08-01 09:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
                (
                    "about_img",
                    cloudinary.models.CloudinaryField(
                        default="placeholder", max_length=255, verbose_name="image"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="about",
            options={},
        ),
        migrations.RemoveField(
            model_name="about",
            name="slug",
        ),
        migrations.AddField(
            model_name="about",
            name="about_img",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
