# Generated by Django 4.2.9 on 2024-07-21 21:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_about_about_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaboraterequest",
            name="about_img",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
