# Generated by Django 4.2.9 on 2024-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juice_app", "0002_category_featured_image_alter_recipe_featured_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
