# Generated by Django 4.2.9 on 2024-07-25 20:02

import cloudinary_storage.storage
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("juice_app", "0003_alter_recipe_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="featured_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="webp",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="juice_category_image/",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="featured_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="webp",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="juice_recipe_image/",
            ),
        ),
    ]
